name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'Ivy-js'
          git config --global user.email 'conctact@1sheol.xyz'

      - name: Make 10 commits
        run: |
          for i in {1..10}; do
            echo "Update #$i" >> update.txt
            git add update.txt
            git commit -m "Automated commit #$i"
          done

      - name: Pull latest changes (rebase)
        run: git pull --rebase origin HEAD

      - name: Force push changes
        run: git push --force origin HEAD
