name: Auto Commit

on:
  workflow_dispatch: # Permet de lancer manuellement le workflow
  schedule:
    - cron: '0 */12 * * *' # Exécution automatique toutes les 12 heures

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Make 10 commits
        run: |
          for i in {1..10}; do
            echo "Update #$i" >> update.txt
            git add update.txt
            git commit -m "Automated commit #$i"
          done

      - name: Push changes
        run: git push origin HEAD
